name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 15
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install Dependencies
        run: npm ci
        env:
          CI: true

      #      - name: Test
      #        run: npm test
      #        env:
      #          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Install Dependencies for Demo Project
        run: npm ci --prefix demo
        env:
          CI: true

      - name: Build Demo Project
        run: npm run build --prefix demo
        env:
          CI: true

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: demo/build

  update-github-pages:
    needs: build
    name: Update Github Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete existing Documentation
        run: find docs ! -name '.gitkeep' -type f -exec rm -f {} +

      - name: Download Documentation Artifact
        uses: actions/download-artifact@v2
        with:
          name: documentation
          path: docs

      - name: Commit and Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Update Documentation"
          git push
