name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/**
      - lerna.json
      - package.json
      - package-lock.json
      - tsconfig.settings.json

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Upload Documentation Artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: packages/demo/build

  update-github-pages:
    needs: build
    name: Update Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Delete existing Documentation
        run: find docs ! -name '.gitkeep' -type f -exec rm -f {} +

      - name: Download Documentation Artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: docs

      - name: Commit and Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Update Documentation"
          git push
